import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createDemoApi } from "./api.js";
import { TOKEN, COMPANY_ID } from "./data.js";
function fixture(signedIn=true) { const values = new Map(); const storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)}; const api=createDemoApi({storage,isSignedIn:()=>signedIn}); const call=(path,method="GET",body)=>api.fetch(`http://127.0.0.1:3000/api/v1${path}`,{method,headers:{Authorization:`Bearer ${TOKEN}`},body:body?JSON.stringify(body):undefined});return{api,call}; }
test("demo requires its isolated session",async()=>{assert.equal((await fixture(false).call("/contacts")).status,401);});
test("dashboard and calls contain fictitious data",async()=>{const {call}=fixture();assert.equal((await(await call("/dashboard/stats")).json()).kpis.calls_7d.inbound,4);assert.equal((await(await call("/calls")).json()).calls.length,4);});
test("cross-tenant and external requests are blocked",async()=>{const {api,call}=fixture();assert.equal((await call("/contacts?company_id=another")).status,403);assert.equal((await api.fetch("https://example.com/api/v1/contacts")).status,403);});
test("paid, provider and invitation actions never succeed",async()=>{const {call}=fixture();for(const p of ["/billing/portal","/billing/checkout","/outbound/campaigns/id/launch","/calendar/oauth/start","/notifications/send-test","/auth/invite","/kb/sources/upload"]) assert.equal((await call(p,"POST",{company_id:COMPANY_ID})).status,403,p);});
test("contact changes persist locally and reset cleanly",async()=>{const{api,call}=fixture();const c=api.getData().contacts[0];await call(`/contacts/${c.id}`,"PATCH",{notes:"Essai local"});assert.equal(api.getData().contacts[0].notes,"Essai local");api.reset();assert.notEqual(api.getData().contacts[0].notes,"Essai local");});
test("support ticket and reply are stored without sending email",async()=>{const{call}=fixture();const r=await call("/tickets","POST",{subject:"Test démo",description:"Essai"});assert.equal(r.status,201);const{ticket}=await r.json();await call(`/tickets/${ticket.id}/messages`,"POST",{body:"Ma réponse"});const d=await(await call(`/tickets/${ticket.id}`)).json();assert.equal(d.messages[0].body,"Ma réponse");});
test("manual knowledge is local; unknown actions fail closed",async()=>{const{call}=fixture();assert.equal((await call("/kb/sources/qa","POST",{question:"Test ?",answer:"Démo"})).status,201);assert.equal((await call("/anything-unknown","POST",{})).status,501);});
test("normal production entry has no demo import or auth bypass",async()=>{const app=await readFile(new URL("../src/App.jsx",import.meta.url),"utf8");const auth=await readFile(new URL("../src/contexts/AuthContext.jsx",import.meta.url),"utf8");assert.doesNotMatch(app,/demo\//);assert.match(auth,/createClient/);assert.doesNotMatch(auth,/local-demo|DEMO_PASSWORD/);const config=await readFile(new URL("../vite.demo.config.js",import.meta.url),"utf8");assert.match(config,/command !== "serve"/);assert.match(config,/config\.server\.proxy = \{\}/);assert.match(config,/host: "127\.0\.0\.1"/);});
