// Public, fictitious credentials. They cannot authenticate with Supabase.
export const DEMO_EMAIL = "client@demo.exevori.test";
export const DEMO_PASSWORD = "DemoVoice2026!";
export const COMPANY_ID = "11111111-1111-4111-8111-111111111111";
export const USER_ID = "22222222-2222-4222-8222-222222222222";
export const TOKEN = "voicedesk-local-demo-only";
export const STORAGE_KEY = "voicedesk.local-demo.v1";
export const SESSION_KEY = "voicedesk.local-demo.session";

export function seed() {
  const date = (hours = 0) => new Date(Date.now() + hours * 3600000).toISOString();
  const company = { id: COMPANY_ID, name: "Atelier Boréal — Démonstration", city: "Lévis", assistant_name: "Léa", status: "active", plan: "essentiel", phone: "+14185550100", contact_email: DEMO_EMAIL, contact_name: "Karim Démo", province: "Québec", billing_country: "CA" };
  const profile = { id: USER_ID, user_id: USER_ID, company_id: COMPANY_ID, full_name: "Karim Démo", email: DEMO_EMAIL, role: "company_admin", status: "active", language: "fr", company, companies: company };
  const contacts = [
    ["Camille Démo", "qualified", "Souhaite un devis pour un entretien", "Rappeler pour confirmer le devis"],
    ["Alex Exemple", "client", "Rendez-vous confirmé pour une consultation", "Préparer le rendez-vous"],
    ["Morgan Démo", "new", "Demande les horaires du samedi", "Répondre à la demande"],
    ["Sam Exemple", "qualified", "Intéressé par un forfait annuel", "Envoyer une proposition"],
  ].map(([full_name, status, main_need, next_action_note], i) => ({ id: `33333333-3333-4333-8333-${String(i + 1).padStart(12, "0")}`, company_id: COMPANY_ID, full_name, status, main_need, next_action_note, next_action: "call", next_action_date: date(24 + i * 4), phone: `+1418555010${i + 1}`, email: `contact${i + 1}@example.test`, company: "Entreprise fictive", notes: "Fiche fictive. Vous pouvez modifier cette note pour tester le CRM.", call_consent: true, email_consent: false, created_at: date(-48 - i * 24), last_interaction_at: date(-i - 1), source: "inbound_call", tags: ["Démonstration"] }));
  const calls = contacts.map((c, i) => ({ id: `44444444-4444-4444-8444-${String(i + 1).padStart(12, "0")}`, company_id: COMPANY_ID, contact_id: c.id, contact: c, caller_name: c.full_name, caller_phone: c.phone, status: i === 2 ? "abandoned" : "completed", direction: "inbound", duration_seconds: [185, 142, 0, 215][i], created_at: date(-i - 1), started_at: date(-i - 1), ended_at: date(-i - 0.9), intent: ["Demande de devis", "Rendez-vous", "Information", "Suivi commercial"][i], ai_summary: `Exemple fictif : ${c.main_need}. ${c.next_action_note}.`, confidence_score: 94, outcome: i === 1 ? "appointment_booked" : "resolved", language_used: "fr-CA", cost_usd: 0, transcript: [{ role: "assistant", text: "Bonjour, vous êtes à l’Atelier Boréal. Je suis Léa, l’assistante virtuelle. Comment puis-je vous aider ?" }, { role: "caller", text: c.main_need }, { role: "assistant", text: "Très bien, j’ai noté votre demande. Un membre de l’équipe assurera le suivi." }] }));
  const appointments = [{ id: "55555555-5555-4555-8555-555555555555", company_id: COMPANY_ID, contact_id: contacts[1].id, contact: contacts[1], contact_name: contacts[1].full_name, invitee_name: contacts[1].full_name, type: "Consultation découverte", title: "Consultation découverte — exemple", date: date(24).slice(0, 10), time: "10:00", starts_at: date(24), ends_at: date(24.5), timezone: "America/Toronto", status: "confirmed", source: "manual", notes: "Rendez-vous fictif : aucune réservation Calendly réelle.", duration_minutes: 30 }];
  const sources = [{ id: "kb-demo-1", company_id: COMPANY_ID, name: "Horaires et accueil", type: "qa", question: "Quels sont vos horaires ?", answer: "Du lundi au vendredi de 9 h à 17 h, sur rendez-vous le samedi.", category: "FAQ", status: "ready", chunks_count: 1, size_bytes: 180, created_at: date(-72) }, { id: "kb-demo-2", company_id: COMPANY_ID, name: "Présentation de l’atelier", type: "manual", answer: "L’Atelier Boréal est une entreprise fictive utilisée pour découvrir VoiceDesk.", category: "Entreprise", status: "ready", chunks_count: 1, size_bytes: 140, created_at: date(-48) }];
  const tickets = [{ id: "66666666-6666-4666-8666-666666666666", company_id: COMPANY_ID, ticket_number: "T-2026-DEMO", subject: "Comment ajuster le message d’accueil ?", description: "Ceci est un exemple de demande au support. Vous pouvez ajouter une réponse fictive.", category: "configuration", priority: "normal", status: "in_progress", created_by_user_id: USER_ID, created_by_name: profile.full_name, created_by_email: DEMO_EMAIL, created_at: date(-2), updated_at: date(-1), first_response_at: date(-1), sla_first_response_due: date(2), sla_resolution_due: date(46) }];
  const messages = [{ id: "message-demo-1", ticket_id: tickets[0].id, company_id: COMPANY_ID, author_name: "Équipe Exevori — Démo", author_role: "exevori_agent", body: "Bienvenue dans cette démonstration ! Vous pouvez modifier le message d’accueil dans Configuration. Aucune modification ne sera envoyée à un fournisseur.", is_internal: false, attachments: [], created_at: date(-1) }];
  const campaigns = [{ id: "77777777-7777-4777-8777-777777777777", company_id: COMPANY_ID, name: "Suivi des demandes — exemple", status: "draft", description: "Campagne fictive ; son lancement réel est bloqué.", total_contacts: 3, completed_contacts: 0, created_at: date(-24), objective: "Confirmer les besoins et proposer un rendez-vous", script: "Bonjour, je vous rappelle au sujet de votre demande.", stats: { total: 3, pending: 3, completed: 0 } }];
  return { company, profile, contacts, calls, appointments, sources, tickets, messages, campaigns,
    config: { company_id: COMPANY_ID, assistant_name: "Léa", assistant_gender: "feminine", tone: "professional", language_primary: "fr-CA", greeting_inbound_fr: "Bonjour, vous êtes à l’Atelier Boréal. Je suis Léa, votre assistante virtuelle.", system_prompt_voice_fr: "Accueillir les clients, prendre les messages et préparer les rendez-vous.", rag_min_similarity: 0.25, settings_sync_status: "not_provisioned" },
    preferences: { ticket_email: true, billing_email: true, weekly_report_email: true, system_email: true },
    notifications: [{ id: "demo-notification-1", company_id: COMPANY_ID, user_id: USER_ID, title: "Bienvenue dans votre espace de démonstration", body: "Explorez les appels, le CRM et le support avec des données fictives.", type: "info", category: "system", event_type: "demo", read: false, link: "/calls", created_at: date() }],
  };
}
